require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: true
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 120

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*"

RSpec/ExampleLength:
  Enabled: False

RSpec/MultipleExpectations:
  Enabled: False

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
